#pragma once

#include "../install/x86_64-elf/include/stdint.h"

enum SysNo
{
    SysRead                = 0,
    SysWrite               = 1,
    SysOpen                = 2,
    SysClose               = 3,
    SysStat                = 4,
    SysFstat               = 5,
    SysLstat               = 6,
    SysPoll                = 7,
    SysLseek               = 8,
    SysMmap                = 9,
    SysMunmap              = 11,
    SysBrk                 = 12,
    SysRtSigaction         = 13,
    SysRtSigprocmask       = 14,
    SysRtSigreturn         = 15,
    SysIoctl               = 16,
    SysPread64             = 17,
    SysPwrite64            = 18,
    SysReadv               = 19,
    SysWritev              = 20,
    SysAccess              = 21,
    SysPipe                = 22,
    SysSelect              = 23,
    SysSchedYield          = 24,
    SysMremap              = 25,
    SysMsync               = 26,
    SysMincore             = 27,
    SysMadvise             = 28,
    SysDup                 = 32,
    SysDup2                = 33,
    SysNanosleep           = 35,
    SysGetitimer           = 36,
    SysAlarm               = 37,
    SysSetitimer           = 38,
    SysGetpid              = 39,
    SysSendfile            = 40,
    SysSocket              = 41,
    SysConnect             = 42,
    SysAccept              = 43,
    SysSendto              = 44,
    SysRecvfrom            = 45,
    SysSendmsg             = 46,
    SysRecvmsg             = 47,
    SysShutdown            = 48,
    SysBind                = 49,
    SysListen              = 50,
    SysGetsockname         = 51,
    SysGetpeername         = 52,
    SysSocketpair          = 53,
    SysSetsockopt          = 54,
    SysGetsockopt          = 55,
    SysClone               = 56,
    SysFork                = 57,
    SysVfork               = 58,
    SysExecve              = 59,
    SysExit                = 60,
    SysWait4               = 61,
    SysKill                = 62,
    SysUname               = 63,
    SysSemget              = 64,
    SysSemop               = 65,
    SysSemctl              = 66,
    SysShmdt               = 67,
    SysMsgget              = 68,
    SysMsgsnd              = 69,
    SysMsgrcv              = 70,
    SysMsgctl              = 71,
    SysFcntl               = 72,
    SysFlock               = 73,
    SysFsync               = 74,
    SysFdatasync           = 75,
    SysTruncate            = 76,
    SysFtruncate           = 77,
    SysGetdents            = 78,
    SysGetcwd              = 79,
    SysChdir               = 80,
    SysFchdir              = 81,
    SysRename              = 82,
    SysMkdir               = 83,
    SysRmdir               = 84,
    SysCreat               = 85,
    SysLink                = 86,
    SysUnlink              = 87,
    SysSymlink             = 88,
    SysReadlink            = 89,
    SysChmod               = 90,
    SysFchmod              = 91,
    SysChown               = 92,
    SysFchown              = 93,
    SysLchown              = 94,
    SysUmask               = 95,
    SysGettimeofday        = 96,
    SysGetrlimit           = 97,
    SysGetrusage           = 98,
    SysSysinfo             = 99,
    SysTimes               = 100,
    SysPtrace              = 101,
    SysGetuid              = 102,
    SysSyslog              = 103,
    SysGetgid              = 104,
    SysSetuid              = 105,
    SysSetgid              = 106,
    SysGeteuid             = 107,
    SysGetegid             = 108,
    SysSetpgid             = 109,
    SysGetppid             = 110,
    SysGetpgrp             = 111,
    SysSetsid              = 112,
    SysSetreuid            = 113,
    SysSetregid            = 114,
    SysGetgroups           = 115,
    SysSetgroups           = 116,
    SysSetresuid           = 117,
    SysGetresuid           = 118,
    SysSetresgid           = 119,
    SysGetresgid           = 120,
    SysGetpgid             = 121,
    SysSetfsuid            = 122,
    SysSetfsgid            = 123,
    SysGetsid              = 124,
    SysCapget              = 125,
    SysCapset              = 126,
    SysRtSigpending        = 127,
    SysRtSigtimedwait      = 128,
    SysRtSigqueueinfo      = 129,
    SysRtSigsuspend        = 130,
    SysSigaltstack         = 131,
    SysUstat               = 132,
    SysStatfs              = 133,
    SysFstatfs             = 134,
    SysSchedSetparam       = 140,
    SysSchedGetparam       = 141,
    SysSchedSetscheduler   = 142,
    SysSchedGetscheduler   = 143,
    SysSchedGetPriorityMax = 144,
    SysSchedGetPriorityMin = 145,
    SysSchedRrGetInterval  = 146,
    SysMlock               = 149,
    SysMunlock             = 150,
    SysMlockall            = 151,
    SysMunlockall          = 152,
    SysVhangup             = 153,
    SysModifyLdt           = 154,
    SysPivotRoot           = 155,
    SysPrctl               = 157,
    SysArchPrctl           = 158,
    SysSetrlimit           = 160,
    SysChroot              = 161,
    SysSync                = 162,
    SysAcct                = 163,
    SysSettimeofday        = 164,
    SysMount               = 165,
    SysUmount2             = 166,
    SysSwapon              = 167,
    SysSwapoff             = 168,
    SysReboot              = 169,
    SysSethostname         = 170,
    SysSetdomainname       = 171,
    SysIopl                = 172,
    SysIoperm              = 173,
    SysInitModule          = 175,
    SysDeleteModule        = 176,
    SysGettid              = 186,
    SysReadahead           = 187,
    SysSetxattr            = 188,
    SysLsetxattr           = 189,
    SysFsetxattr           = 190,
    SysGetxattr            = 191,
    SysLgetxattr           = 192,
    SysFgetxattr           = 193,
    SysListxattr           = 194,
    SysLlistxattr          = 195,
    SysFlistxattr          = 196,
    SysRemovexattr         = 197,
    SysLremovexattr        = 198,
    SysFremovexattr        = 199,
    SysTkill               = 200,
    SysTime                = 201,
    SysFutex               = 202,
    SysSchedSetaffinity    = 203,
    SysSchedGetaffinity    = 204,
    SysSetThreadArea       = 205,
    SysIoSetup             = 206,
    SysIoDestroy           = 207,
    SysIoGetevents         = 208,
    SysIoSubmit            = 209,
    SysIoCancel            = 210,
    SysGetThreadArea       = 211,
    SysLookupDcookie       = 212,
    SysEpollCreate         = 213,
    SysEpollCtlOld         = 214,
    SysEpollWaitOld        = 215,
    SysRemapFilePages      = 216,
    SysGetdents64          = 217,
    SysSetTidAddress       = 218,
    SysRestartSyscall      = 219,
    SysSemtimedop          = 220,
    SysFadvise64           = 221,
    SysTimerCreate         = 222,
    SysTimerSettime        = 223,
    SysTimerGettime        = 224,
    SysTimerGetoverrun     = 225,
    SysTimerDelete         = 226,
    SysClockSettime        = 227,
    SysClockGettime        = 228,
    SysClockGetres         = 229,
    SysClockNanosleep      = 230
};

/*SysMac*/
#define Syscall(__SysNum__, __Arg1__, __Arg2__, __Arg3__, __Arg4__, __Arg5__, __Arg6__)            \
    ({                                                                                             \
        int64_t result;                                                                            \
        __asm__ volatile("movq %1, %%rax\n\t" /* syscall __SysNum__ber */                          \
                         "movq %2, %%rdi\n\t" /* __Arg1__ */                                       \
                         "movq %3, %%rsi\n\t" /* __Arg2__ */                                       \
                         "movq %4, %%rdx\n\t" /* __Arg3__ */                                       \
                         "movq %5, %%r10\n\t" /* __Arg4__ */                                       \
                         "movq %6, %%r8\n\t"  /* __Arg5__ */                                       \
                         "movq %7, %%r9\n\t"  /* __Arg6__ */                                       \
                         "int $0x80\n\t"      /* syscall interrupt */                              \
                         "movq %%rax, %0"                                                          \
                         : "=r"(result)                                                            \
                         : "r"((uint64_t)(__SysNum__)),                                            \
                           "r"((uint64_t)(__Arg1__)),                                              \
                           "r"((uint64_t)(__Arg2__)),                                              \
                           "r"((uint64_t)(__Arg3__)),                                              \
                           "r"((uint64_t)(__Arg4__)),                                              \
                           "r"((uint64_t)(__Arg5__)),                                              \
                           "r"((uint64_t)(__Arg6__))                                               \
                         : "rax", "rdi", "rsi", "rdx", "r10", "r8", "r9", "memory");               \
        result;                                                                                    \
    })